Log in with PayPal Button from JS SDK
paypal/paypal-sdk-spec pull request #55
Opened 2021-09-30 21:54 UTC by Karthickgreets99

## Description

Log in with PayPal the new Connect with PayPal button does not support return_uri parameter, and instead a callback (onApprove) has to be defined. The generated auth_code will be passed as an argument to the callback.

#tech design

https://engineering.paypalcorp.com/confluence/display/IdentityPlatform/Connect+JS+SDK+button+-+requirements#ConnectJSSDKbuttonrequirements-Technicaldesign

2021-09-30 22:12 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +const onApprove = (data) => {
What data is returned by the `onApprove` callback? It would be good to document the object shape.

2021-09-30 22:13 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +                // locale : 'en_FR',
We should not accept locale here as it's already a global sdk param.

2021-09-30 22:14 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +const onCancel = (data) => {
Can you provide an example of the declined consent use case?

2021-09-30 22:14 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +                returnurl: "https://google.com",
Why accept a return url when we have the `onApprove` callback?

2021-09-30 22:14 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +- Pass [`components=auth-button`](../../initialization.md#intent)
Is this the right link?

2021-09-30 22:16 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
Shouldn't this be an array of strings, rather than an array with a single string in it?

2021-09-30 22:17 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +2. We have 4 different labels to support
Please add a page with all of the style options and values you can pass.

2021-09-30 22:17 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +1. client_id (in query param)
Please make sure these steps are 100% exact with the correct spelling and casing. e.g. `client-id`, `responseType`, etc.

2021-09-30 22:19 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +             {
Please follow the coding style and indentation of the other examples for `paypal.Buttons`

2021-09-30 22:53 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                // locale : 'en_FR',
we should see how content is loaded from ICE , we need this locale to be pass as part of our IdentityClientExperience

2021-09-30 23:30 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +we need 5 mandate parameteres from partner to provide the button to be apprear in their integration place.
```suggestion
The following parameters are mandatory for the auth button:
```

2021-09-30 23:33 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +                responseType: 'id_token',
Can you add a page which lists the allowed scopes and response types

2021-10-01 02:30 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +const onCancel = (data) => {
i have attach the screenshot of Cancel consent and code 

![Screen Shot 2021-09-30 at 7 29 35 PM](https://user-images.githubusercontent.com/4567452/135556359-d89a0e7f-c127-46d1-8ff8-80797a426958.png
![Screen Shot 2021-09-30 at 7 30 14 PM](https://user-images.githubusercontent.com/4567452/135556409-8dc8b088-1369-4c64-bbb6-4cc83edfd30c.png)
)

2021-10-01 02:31 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                returnurl: "https://google.com",
This Return url needs for Connect to up and running this is mandatory parameters

2021-10-01 02:33 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
we have that nice to have in phase 2 release

2021-10-01 02:35 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +2. We have 4 different labels to support
![Screen Shot 2021-09-30 at 7 33 32 PM](https://user-images.githubusercontent.com/4567452/135556659-b554cc4f-119d-462d-8d4b-4306d71c9c01.png)

color supported for LIPP , 
Silver and blue
labels supported for LIPP
1. Connect with PayPal
2. Log in with PayPal
3. Continue with PayPal
4. Sign up with PayPal

2021-10-01 03:30 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +1. client_id (in query param)
we have the responseType and clientId params , i have update the type

2021-10-01 03:32 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +we need 5 mandate parameteres from partner to provide the button to be apprear in their integration place.
done

2021-10-01 03:33 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                responseType: 'id_token',
The scopes are dynamic based on clientId and the account they create with PayPal. 

Response type are code , code_id_token, id_token

2021-10-01 03:34 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +             {
done

2021-10-01 17:52 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +            returnurl: "https://google.com",
Can we rename this to redirectUrl to match other parts of the sdk?
```suggestion
            redirectUrl: "https://google.com",
```

2021-10-01 17:57 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +            responseType: 'id_token',
Let's make a note that "id_token" and "auth_code"

2021-10-01 18:04 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +                style : {
Let's fix this indenting:
```suggestion
            style : {
```

2021-10-01 18:09 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +1. client_id (in query param)
The `client-id` and `components=auth-button` are technically query string parameters for the sdk. I think we should remove them from this Button props list and instead only mention them in the SDK Initialization section above.

2021-10-01 18:12 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +            onApprove:function (data) {
@Karthickgreets99 and I synced around the `onApprove` behavior. I learned that the payload object shape is dependent on the `responseType` Button prop value. Ex:

### id_token

```js
paypal.AuthButton({
  scopes: ['openid profile email address phone'],
  responseType: 'id_token',   
  redirectUrl: "https:/www.google.com",
  onApprove: data => {
    // this will return the id token in the payload
    // data = { idToken: "<value>" }
  }
});
```
### auth_code

```js
paypal.AuthButton({
  scopes: ['openid profile email address phone'],
  responseType: 'auth_code',   
  redirectUrl: "https:/www.google.com",
  onApprove: data => {
    // this will return the authCode in the payload
    // data = { authDode: "<value>" }
  }
});
```

2021-10-01 23:02 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            onApprove:function (data) {
Cool, let's include this in the spec.

2021-10-01 23:03 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            returnurl: "https://google.com",
I'm not sure where my comment went... but we should remove this entirely. It's a bad DX to request a url that is never redirected to.

2021-10-01 23:06 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            scopes: ['openid profile email address phone'],
Comment got lost -- this should be an array of multiple strings right? Not a single string?

2021-10-01 23:07 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +```javascript
Please fix all of the indentation to match the other button spec.

2021-10-02 07:44 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
we are thinking of existing mechants also adapt to the new button, the existing merchants are integrated like this.

2021-10-04 00:22 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +            scopes: ['openid profile email address phone'],
The reason we kept as a single string in an array because 
1. Existing partners are integrated like this in the old  LIPP button , we want to make minimal impact to migrate them to the new button.
2. We can make that change

2021-10-04 14:55 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +            returnurl: "https://google.com",
@bluepnume that's a good point. I'm in favor of removing assuming we can get the value another way for the Connect app. 

@Karthickgreets99 what does Connect need this value for? Is it the merchant domain that's needed? If so, we have a convention for getting this from the sdk in the app doing the second render using `xprops.getParentDomain()`. For example, here's how we do this in smart-payment-buttons:
https://github.com/paypal/paypal-smart-payment-buttons/blob/1e02d5100201d76f95a330f65c0a4a1585e7bfb1/src/props/props.js#L213


<img width="1200" alt="Screen Shot 2021-10-04 at 9 50 21 AM" src="https://user-images.githubusercontent.com/534034/135873988-144d1077-f40d-460f-b673-24baae9428a7.png">

2021-10-04 15:00 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +                // locale : 'en_FR',
@Karthickgreets99 each component of the sdk needs to leverage the same global locale command for managing the sdk locale. That way when merchants are using multiple paypal components on the same page, they language text all matches (ex: messages, buttons, auth-button).

```js
// global function for getting the locale
import { getLocale } from '@paypal/sdk-client/src';
```

Here's an example to follow for how checkout-components manages this locale prop:
https://github.com/paypal/paypal-checkout-components/blob/master/src/zoid/buttons/component.jsx#L164-L168

2021-10-04 15:04 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
I asked about this one at first as well. Having the merchants upgrade to the JS SDK is a good opportunity to change props as well. 

@Karthickgreets99 can you provide a few different examples of how `scopes` is used by merchants? The current approach of a single string of space-delimited keywords inside an array is usual and confusing for JavaScript developers. 

Instead, I would expect it to be `scopes: ['openid', 'profile', 'email', 'address', 'phone']`.

2021-10-04 17:10 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
@gregjopa  we have changed to  scopes: ["openid", "profile", "email", "address", "phone"]

2021-10-04 17:27 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +                scopes: ['openid profile email address phone'],
Great to hear! 😄

2021-10-04 18:03 UTC, bluepnume commented
Looks like the tests are failing. Can you try `npm test` locally?

2021-10-04 18:06 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +2. We have 4 different labels to support
Sounds good. Can you please add a `style.md` similar to the checkout buttons which shows all these options?

2021-10-04 18:11 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            scopes: ['openid profile email address phone'],
Yeah let's make the change :) better to be consistent with new integrations when we have the chance, versus maintaining old patterns which don't make sense.

2021-10-04 18:11 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            responseType: 'id_token',
Yep it would be good to have a page, or at least a section, which lists and explains the different response types.

2021-10-04 18:13 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            returnurl: "https://google.com",
Discussed on call: the best way forward here is:

- Short term: using `urn:ietf:wg:oauth:2.0:oob` as the return url, or configuring a list of pilot merchants
- Long term: finding some other way to avoid this url requirement. Or just use `urn:ietf:wg:oauth:2.0:oob` as the long term approach.

Either way: want to avoid this parameter, even in the short term. Once we add it we can never take it back.

2021-10-04 19:41 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                returnurl: "https://google.com",
we are removing the parameter

2021-10-04 20:34 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +- Pass [`components=auth-button`](../../initialization.md#intent)
done

2021-10-04 20:37 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +1. client_id (in query param)
done

2021-10-04 20:38 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +            returnurl: "https://google.com",
this been sorted out we  are configuring returnurl in config to read.

2021-10-04 20:44 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +            scopes: ['openid profile email address phone'],
done

2021-10-04 22:58 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +2. We have 4 different labels to support
added styles.md, please verify

2021-10-04 23:16 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +```javascript
done

2021-10-04 23:17 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +const onApprove = (data) => {
i have added the object shape in data.md file

2021-10-04 23:17 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +                style : {
done

2021-10-05 17:42 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/index.md
> +                // data = { idToken: "<value>" } , { auth_code : "<value>"}
```suggestion
                // data = { idToken: "<value>" } , { authCode : "<value>"}
```

2021-10-05 17:49 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/layouts.md
> +# Button Layouts
I don't think we need this page right? You don't support multiple layouts in this button right?

2021-10-05 17:50 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/style.md
> +#### LIPP PayPal Button
We can remove this section if it's just blue and silver

2021-10-05 17:50 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/style.md
> +1. Blue
`blue`

2021-10-05 17:50 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/style.md
> +2. silver
`silver`

2021-10-05 17:55 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            responseType: 'id_token',
Can you please add a page which explains what `id_token` and `auth_code` mean?

2021-10-05 17:57 UTC, bluepnume commented on spec/client/javascript/callbacks/onApprove-consent.md
> +        // this return value depends on reponseType parameter
There are quite a few typos in this doc, like reponseType should be responseType. Can you please take a look and fix these? This will be a public-facing document so needs to be exact :)

2021-10-05 17:58 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +    - Pass [`components=auth-button`](../../callbacks/onApprove-consent.md)
This link still doesn't seem correct, right?

2021-10-05 18:00 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/data.md
> +                {"id_token":"eyJraWQiOiI2ZGJhNWZiNzkzZDc0MTZhOGZkNmE0ZDJiZjYyZDI1NiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2FwaS5tc21hc3Rlci5xYS5wYXlwYWwuY29tIiwic3ViIjoiaHR0cHM6Ly
Let's be consistent with naming. Should probably use `idToken` instead of `id_token`

2021-10-05 18:00 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/data.md
> +    Cancel_code :
What is this? Where will it be passed?

2021-10-05 18:00 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +    1. client-id (mandate)
mandatory

2021-10-05 18:02 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +            {
Code formatting is still weird, please make it match the other buttons.

2021-10-05 18:03 UTC, bluepnume commented on spec/client/javascript/components/AuthButton/index.md
> +                style : {
Indendation

2021-10-05 18:40 UTC, gregjopa commented on spec/client/javascript/components/AuthButton/data.md
> +    Cancel_code :
I was also wondering abut this cancel use case. I think of `onCancel` as the user closing the popup window and abandoning the flow. Wondering if this unhappy path needs to consider `onError` instead of `onCancel`

2021-10-05 19:11 UTC, crookedneighbor requested changes

2021-10-05 19:11 UTC, crookedneighbor commented on spec/client/javascript/components/AuthButton/data.md
> +                {"authCode":"C21_A.AAcEExqLo6wTYm0agGbMVXjbGnVSApmfA_TrdDhfsY-XBHfcv6uFUWQ2X07exNb6vv7O_15wKnI1JCY2J6QlEdKLwJdyRg"}
```suggestion
                {"authCode":"<generated-auth-code-token>"}
```

2021-10-05 19:11 UTC, crookedneighbor commented on spec/client/javascript/components/AuthButton/data.md
> +                {"id_token":"eyJraWQiOiI2ZGJhNWZiNzkzZDc0MTZhOGZkNmE0ZDJiZjYyZDI1NiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2FwaS5tc21hc3Rlci5xYS5wYXlwYWwuY29tIiwic3ViIjoiaHR0cHM6Ly
```suggestion
                {"id_token":"<generated-id-token>"}
```

2021-10-05 19:11 UTC, crookedneighbor commented on spec/client/javascript/components/AuthButton/index.md
> +    1. client-id (mandate)
```suggestion
    1. client-id (mandatory)
```

2021-10-05 19:11 UTC, crookedneighbor commented on spec/client/javascript/components/AuthButton/index.md
> +    2. component (mandate)
```suggestion
    2. component (mandatory)
```

2021-10-05 22:33 UTC, gregjopa commented on spec/client/javascript/components/auth-button/rendering.md
> +- Pass [`components=auth-button`](../../initialization.md#components)
We weren't sure the best spot to put this sdk intitialization code. It's just one line so I was hesitant to create a `sdk-initialization.md` file for it.

2021-10-05 22:34 UTC, gregjopa commented on spec/client/javascript/components/auth-button/rendering.md
> +Log in with PayPal (LIPP) button is now integrated via JS SDK to Log in with your paypal account from any partner.
I'm thinking we remove this text to keep this content focused on just the spec.

```suggestion
```

2021-10-05 22:38 UTC, bluepnume commented on spec/client/javascript/callbacks/README.md
> +- [onApprove:Consent](./onApprove-consent.md)
Can we call this `onApprove:Auth` to disambiguate?

2021-10-05 22:39 UTC, bluepnume commented on spec/client/javascript/components/auth-button/scopes.md
> +        scopes: ["openid", "profile", "email", "address", "phone"],
Can you add some bullet points for the available scopes, and what they allow?

2021-10-05 22:40 UTC, bluepnume commented on spec/client/javascript/components/auth-button/rendering.md
> +Log in with PayPal (LIPP) button is now integrated via JS SDK to Log in with your paypal account from any partner.
Agreed

2021-10-05 22:40 UTC, bluepnume commented on spec/client/javascript/callbacks/onApprove-consent.md
> +    authCode : string,
Will there always be an authCode even in idToken case? Or should this be `authCode? : string`?

2021-10-05 22:51 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onApprove-consent.md
> +    authCode : string,
yes in idToken responseType we have authcode too in th object

2021-10-05 22:52 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/scopes.md
> +        scopes: ["openid", "profile", "email", "address", "phone"],
@bluepnume it is all based on how partner integrate with PayPal , it is very huge list of scopes to have it here. we just providing some sample

2021-10-05 22:53 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/README.md
> +- [onApprove:Consent](./onApprove-consent.md)
Yeah that make more meaning

2021-10-05 22:53 UTC, bluepnume commented on spec/client/javascript/components/auth-button/scopes.md
> +        scopes: ["openid", "profile", "email", "address", "phone"],
In that case can you add a link where someone can find out more? This must be in some doc right?

2021-10-05 23:25 UTC, gregjopa commented on spec/client/javascript/components/auth-button/README.md
> +- [Styling](./style.md)
Let's rename this file to styling.md to match the pattern for other components.
```suggestion
- [Styling](./styling.md)
```

2021-10-05 23:46 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onApprove-consent.md
> +        // this return value depends on reponseType parameter
done

2021-10-05 23:48 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/README.md
> +- [Styling](./style.md)
done

2021-10-05 23:58 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/scopes.md
> +        scopes: ["openid", "profile", "email", "address", "phone"],
this is sample documentation , but etire scopes are not revealed 
https://developer.paypal.com/docs/log-in-with-paypal/integrate/reference/#scope-attributes

2021-10-06 05:05 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/data.md
> +                {"authCode":"C21_A.AAcEExqLo6wTYm0agGbMVXjbGnVSApmfA_TrdDhfsY-XBHfcv6uFUWQ2X07exNb6vv7O_15wKnI1JCY2J6QlEdKLwJdyRg"}
done

2021-10-06 05:05 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/index.md
> +    2. component (mandate)
done

2021-10-06 16:03 UTC, gregjopa commented on spec/client/javascript/components/auth-button/response-type.md
> +            responseType: 'code',
Can we assign a default value for `responseType`? Perhaps the default can be `code` since that seems like the most common use case.

2021-10-06 19:34 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +Callback used to signal partner once user accept the consent
```suggestion
Callback used to signal user consent approval from successfully completing the auth button flow.
```

2021-10-06 19:36 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +- Successfully return auth_code and id_token based on responseType provided by partner.
I think we can drop this since it's explained by the examples below.
```suggestion
```

2021-10-06 19:42 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +### Get auth_code/id_token from paypal
Thinking we can keep this heading general to apply to both types of tokens.
```suggestion
### Get authorization tokens
```

2021-10-06 19:50 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +const onApprove = (data) => {
From my understanding, users of this auth button will send these tokens to their server-side api so they can later pull user info from the identity endpoints ex: https://developer.paypal.com/docs/api/identity/v1/#userinfo_get. If that's the case, can we illustrate it with a fetch call like so:
```js
const onApprove = (data, actions) => {
    // merchant sends auth tokens to their own api to
    // lookup additional user info using the paypal identity apis
    return fetch('/api/paypal/auth/consent', {
        method: 'POST',
        body: JSON.stringify({
            authCode: data.authCode
            idToken: data.idToken
        })
    }).then(res => {
        // Show a success message to the user
    });
};
```

2021-10-08 05:29 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onApprove-consent.md
> +Callback used to signal partner once user accept the consent
done

2021-10-08 05:30 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onApprove-consent.md
> +const onApprove = (data) => {
done

2021-10-08 14:10 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +### Get auth_code/id_token from paypal
I don't see this change made. @Karthickgreets99 can you take another look?

2021-10-08 14:14 UTC, gregjopa commented on spec/client/javascript/components/auth-button/styling.md
> +### Available Labels
@Karthickgreets99 can we remove this `Available Labels` section since it's duplicating content listed above?

2021-10-08 14:15 UTC, gregjopa commented on spec/client/javascript/components/auth-button/styling.md
> +
```suggestion
```

2021-10-08 17:04 UTC, Karthickgreets99 commented on spec/client/javascript/components/AuthButton/layouts.md
> +# Button Layouts
we removed it

2021-10-12 19:01 UTC, gregjopa commented on spec/client/javascript/callbacks/onApprove-consent.md
> +
Can you add the types for the `data` payload for `onCancel`? I'm not sure the exact shape so it will be great to type it out. Something like:

```js
type OnCancelData = {
    errorCode: "",
    errorMessage: ""
};
```

2021-11-01 21:05 UTC, gregjopa approved these changes
Looks good to me! Nice work @Karthickgreets99 💯

2021-11-03 19:03 UTC, crookedneighbor requested changes

2021-11-03 19:03 UTC, crookedneighbor commented on spec/client/javascript/components/auth-button/scopes.md
> +</table>
Can we use a markdown table instead?

```suggestion
| User Attribute | Category | Scope Value |
| -------------- | -------- | ----------- |
| None | Basic Authentication | `openid` |
| Full Name | Personal Information | `profile` |
| Email address | Address Information | `email` |
| Street address | Address Information | `address` |
| City | Address Information | `address` |
| State | Address Information | `address` |
| Country | Address Information | `address` |
| Zip code | Address Information | `address` |
```

it'll end up looking like this:

| User Attribute | Category | Scope Value |
| -------------- | -------- | ----------- |
| None | Basic Authentication | `openid` |
| Full Name | Personal Information | `profile` |
| Email address | Address Information | `email` |
| Street address | Address Information | `address` |
| City | Address Information | `address` |
| State | Address Information | `address` |
| Country | Address Information | `address` |
| Zip code | Address Information | `address` |

2021-11-09 23:34 UTC, andyfen commented on spec/client/javascript/callbacks/onApprove-auth.md
> +) => undefined | Promise<undefined>
should this be `void | Promise<void>` ?

2021-11-10 20:28 UTC, crookedneighbor commented on spec/client/javascript/callbacks/onApprove-auth.md
> +) => undefined | Promise<undefined>
:+1: on `void | Promise<void>`

2021-11-10 22:17 UTC, bluepnume commented on spec/client/javascript/callbacks/onApprove-auth.md
> +) => undefined | Promise<undefined>
This is TypeScript, so I think either is acceptable. Although `void` is perhaps a little more correct, since it signifies that the response will not be consumed ever.

2021-12-20 16:02 UTC, gregjopa commented
@Karthickgreets99 can you address @crookedneighbor's comments/suggestions? It would be great to get those resolved so we can merge this PR before the end of the year.

2022-01-26 20:15 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onCancel-auth.md
> +    // data will contain information about the canceled consent request
done

2022-01-26 20:15 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onCancel-auth.md
> +};
added comments

2022-01-26 20:29 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/scopes.md
> +</table>
changed the table

2022-01-26 20:30 UTC, Karthickgreets99 commented
@crookedneighbor Can you please review and let me know if you have any more comments, Sorry i missed it and after that i went for PTO.

2022-01-27 16:02 UTC, crookedneighbor requested changes
@Karthickgreets99 started to leave a review of this, but it looks like maybe you made some changes locally that haven't been pushed up? I see lots of comments about changes you've made, but it still looks like the version I reviewed before.

2022-01-27 16:02 UTC, crookedneighbor commented on spec/client/javascript/components/auth-button/response-type.md
> +    }
^ Did you want to use the shorthand here? Or still go with the arrow function version?

2022-01-27 16:02 UTC, crookedneighbor commented on spec/client/javascript/components/auth-button/scopes.md
> +</table>
The more I look at this, the more I think there are some local changes you've made that haven't been pushed up yet.

2022-01-28 05:41 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onApprove-auth.md
> +};
its up to partner how do they want to handle on approve consent and treat the approve action. for ex : may be they redirect or they may have to show success message or they can able to complete transaction. We are just giving the skeleton for the partner.

2022-01-28 05:42 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/response-type.md
> +    }
either ways it is fine.

2022-01-28 05:45 UTC, Karthickgreets99 commented
@crookedneighbor  update the branch it was not pushed from my end.

2022-01-31 15:16 UTC, crookedneighbor requested changes

2022-01-31 15:16 UTC, crookedneighbor commented on spec/client/javascript/callbacks/onCancel-auth.md
> +};
Can these be filled out or use the [TODO tag](https://github.com/paypal/paypal-sdk-spec#tags)?

2022-01-31 20:16 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onCancel-auth.md
> +    // sample data object {"errorCode":"Consent denied"}
it is a string message

2022-01-31 20:26 UTC, crookedneighbor commented on spec/client/javascript/callbacks/onCancel-auth.md
> +    // sample data object {"errorCode":"Consent denied"}
why is that? Do you really want integrators to integrate like this?

```javascript
onCancel(data) {
  // data.errorCode - a human readable string
  switch (data.errorCode) {
    case "Consent denied":
      // handle consent denied case
    case "Some other message":
      // handle some other other error case
    default:
      // handle all other cases
  }
}
```

Instead of something more like this:

```javascript
onCancel(data) {
  // data.errorCode - an enum string
  // data.errorMessage - a human readable string
  switch (data.errorCode) {
    case paypal.AuthButton.errors.CONSENT_DENIED:
      // handle consent denied case
    case paypal.AuthButton.errors.OTHER_ERROR:
      // handle some other other error case
    default:
      // handle all other cases
  }
}
```

Where you have a `errorCode` property that is guaranteed to not change, and an `errorMessage` that is a human readable representation of the error, but has the freedom to change or add new information from the API as needed?

2022-01-31 20:42 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onCancel-auth.md
> +    // sample data object {"errorCode":"Consent denied"}
@crookedneighbor  point taken, since we get a string from downstream we usually send that to partner or integrators, now we are looking for callback function or something for the next action we can provide some enum to partners to verify and that we have to provide from PayPal-identity-components not from API, i highly doubt we can change the API response.

2022-01-31 20:43 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/response-type.md
> +```
@crookedneighbor why we want to remove this, i didnt get that ?

2022-01-31 20:44 UTC, Karthickgreets99 commented on spec/client/javascript/components/auth-button/rendering.md
> +```
@crookedneighbor  to maintain uniformity i took the reference from other pages the syntax looks the same, why do we want to remove, i didnt get that, can you please provide some insights ?

2022-01-31 20:57 UTC, Karthickgreets99 commented on spec/client/javascript/callbacks/onCancel-auth.md
> +};
done

2022-01-31 21:26 UTC, Karthickgreets99 commented
@crookedneighbor updated the PR accordingly.

2022-01-31 22:09 UTC, crookedneighbor commented on spec/client/javascript/components/auth-button/response-type.md
> +```
I think the github markdown parser didn't interpret it correctly. I was trying to add an additional line break.

2022-01-31 22:09 UTC, crookedneighbor approved these changes

2022-02-01 15:53 UTC, merged