add payment fields component spec
paypal/paypal-sdk-spec pull request #75
Opened 2021-11-04 21:50 UTC by andyfen

2021-11-08 17:30 UTC, crookedneighbor requested changes

2021-11-08 17:30 UTC, crookedneighbor commented on spec/client/javascript/components/payment-fields/README.md
> +# Payment Fields
Can we add something that gives an explanation for what these are?

```suggestion
# Payment Fields

This component allows customers to pay with payment methods that are only available in certain locations.
```

2021-11-08 17:30 UTC, crookedneighbor commented on spec/client/javascript/components/payment-fields/styling.md
> +
```suggestion
```

2021-11-10 21:24 UTC, bluepnume commented on spec/client/javascript/components/payment-fields/styling.md
> +### Properties
Can you work with @leogedler to agree on a common naming format and set of properties between these fields and the card fields? Would be good to make sure they're consistent: https://github.com/paypal/paypal-sdk-spec/blob/main/spec/client/javascript/components/card-fields/styling.md

2021-11-10 21:27 UTC, bluepnume commented
This is looking great, thanks @andyfen!

In some of the examples can you show how this works end-to-end; e.g. with the button component, rendering, getting a click, creating an order and getting a successful approval?

2021-11-11 15:38 UTC, leogedler commented on spec/client/javascript/components/payment-fields/styling.md
> +### Properties
@andyfen We have here the most updated styles supported for card-fields: https://github.com/paypal/paypal-smart-payment-buttons/blob/master/src/card/constants.js#L29

And here an example on how we are passing the style object into the cardFields component: https://github.com/paypal/paypal-sdk-samples/pull/1/files#diff-0a7b080f4b388288a16e65bf73e045b1f6b6402151baab2a13485aa33780ac1eR135

2021-11-22 21:04 UTC, crookedneighbor commented on spec/client/javascript/components/payment-fields/README.md
> +# Payment Fields
Love the explanation you added. 

Is there some context on why the name "Payment Fields" was chosen for this product? It sounds pretty generic, and I'd never guess that these localized payment methods would be included under it. (not that I have a good name to replace it with, just curious)

2022-05-11 21:43 UTC, closed without merging