Card fields simple integrations steps
paypal/paypal-sdk-spec pull request #76
Opened 2021-11-10 20:15 UTC by leogedler

Created files with the simple integration steps for the unbranded single card fields and multi card fields with custom button.

Jira tickets:
- https://engineering.paypalcorp.com/jira/browse/DTNOR-268
- https://engineering.paypalcorp.com/jira/browse/DTNOR-269

2021-11-10 20:21 UTC, crookedneighbor approved these changes

2021-11-10 21:17 UTC, bluepnume commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +        branded: false,
Thinking we should leave this out of the simple steps. We should automatically be in unbranded mode for eligible merchants.

2021-11-10 21:43 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +        branded: false,
Got it. Removed!

2021-11-30 22:32 UTC, nbierdeman reviewed
Great job, @leogedler! I left some mostly minor comments regarding the multi card fields integration steps. I'll work on the single card fields integration steps in a separate review.

2021-11-30 22:32 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
For some reason, I'm getting the following error, but only for `cardFields.CVVField()`:

<img width="1755" alt="Screen Shot 2021-11-30 at 3 14 47 PM" src="https://user-images.githubusercontent.com/20399044/144136805-8fc985c9-9c2e-4d19-ac1a-a2ebe6a644e3.png">

2021-11-30 22:32 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +
```suggestion
```

2021-11-30 22:32 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +        cardField.submit().then(() => {
```suggestion
        cardFields.submit().then(() => {
```

2021-11-30 23:42 UTC, nbierdeman reviewed
@leogedler, looking good! I tried to stay consistent with my suggestions for both of the integration samples. Sorry in advance if I missed something.

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    const button = buttonContainer.querySelector("#button");
```suggestion
    const cardContainer = document.querySelector("#card-field-container");
    const button = document.querySelector("#button");
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +#### 2. Create container elements for the fields and the button
```suggestion
#### 2. Create container elements for cardFields and the button
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +#### 3. Initialize cardFields component passing createOder and onApprove and call render and passing the styles object
```suggestion
#### 3. Initialize the cardFields component, pass in createOrder, onApprove, and the styles object, and call render
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +
```suggestion
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +            // Create the order in your server and return the order id
```suggestion
            // Create the order on your server and return the order id
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +            console.log("Payment Approved: ", data, actions);
Should this be moved down to `// Handle Successful transaction`?

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +            // Capture the order in your server with order ID `orderID`
```suggestion
            // Capture the order on your server with `orderID`
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +
```suggestion
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +
```suggestion
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
For some reason, I'm getting the following error when clicking the button:

![Screen Shot 2021-11-30 at 4 33 59 PM](https://user-images.githubusercontent.com/20399044/144145014-fb658a60-43f4-46be-bb1e-041643eafa8f.png)

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    button.addEventListener("click", () => {
Just to match the style of the multi card fields integration sample:
```suggestion
    button.addEventListener('click', () => {
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/validation.md
> +        cardFieldContainer.className = data.isValid ? 'valid' : 'invalid';
```suggestion
        cardContainer.className = data.isValid ? 'valid' : 'invalid';
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/validation.md
> +        cardCVVContainer.className = data.isValid ? 'valid' : 'invalid';
```suggestion
        cardCvvContainer.className = data.isValid ? 'valid' : 'invalid';
```

2021-11-30 23:42 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/validation.md
>  }).render(cardCVVContainer);
```suggestion
}).render(cardCvvContainer);
```

2021-11-30 23:48 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +                // Handle Successful transaction
```suggestion
                // Handle successful transaction
```

2021-12-01 14:01 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
@nbierdeman I'll check

2021-12-01 14:01 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
@nbierdeman I'll check

2021-12-01 14:02 UTC, leogedler commented
@nbierdeman thanks for the review, I'll push your suggestions and check the errors.

2021-12-01 16:23 UTC, crookedneighbor commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    const button = buttonContainer.querySelector('#button');
Alternatively, use `document.getElementById` since these are all ids, which I believe is technically faster than `document.querySelector` (though, at the number of elements we're querying for, won't make a noticeable difference)

2021-12-01 17:05 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    const button = buttonContainer.querySelector('#button');
Great suggestion. Thanks!

2021-12-01 17:09 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    const button = buttonContainer.querySelector("#button");
@leogedler, @crookedneighbor previously suggested we use `document.getElementById` instead of `document.querySelector`, which I think is a great idea for here too.

2021-12-01 17:24 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    const button = buttonContainer.querySelector('#button');
I'll implement the suggestion.

2021-12-01 17:58 UTC, rsdighe76 requested changes

2021-12-01 17:58 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 4. Initialize card fields components, call render for each field, and pass in the styles object
what would it mean in this step to have the out of box experience that Nidaul has in their design ? can we add all those styling elements here ?

2021-12-01 17:58 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 3. Initialize the parent cardFields component and pass in createOrder and onApprove
is there a reason why we would do this prior to styling. I would imagine the developer but put the buttons get it showed up correctly and then do the work to integrate particularly on the API side

2021-12-01 17:58 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +#### 3. Initialize the cardFields component, pass in createOrder, onApprove, and the styles object, and call render
why isn't "styling" and "createOrder , onApprove" etc two distinct steps

2021-12-01 17:58 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    const customStyles = {
what additions do we need to make so that we can deliver an out of box experience similar to what Nidaul has defined.

2021-12-01 17:59 UTC, rsdighe76 requested changes

2021-12-01 17:59 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +<script src="https://www.paypal.com/sdk/js?client-id=test&components=card-fields&intent=capture"></script>
why do we have intent as part of the script tag for this example ?

2021-12-01 18:20 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +<script src="https://www.paypal.com/sdk/js?client-id=test&components=card-fields&intent=capture"></script>
@rsdighe76 we need to differentiate between `capture`, `authorize` and `tokenize`.

This first implementation if for capturing but Daniel laid down the logic for the other two options.

2021-12-01 18:20 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 3. Initialize the parent cardFields component and pass in createOrder and onApprove
@rsdighe76 `CardFields` is the parent component and each individual field (`NumberField`, `CVVField` and `ExpiryField`) is a child.

The parent component (CardFields) need to be instantiated first and after that each children e.g.: `cardFields.NumberField(...)` accepts  the `style` options on instantiation, that is why for the multi card fields we need to first instantiate the parent in the `step 3` and the on `step 4` each field with any option that we want to pass in (In this case the styles).

2021-12-01 18:20 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 4. Initialize card fields components, call render for each field, and pass in the styles object
@rsdighe76 partially yes.

We also need to add some styles to the container element (html/JS) and that is not an option that we pass in to the component.

The complete styles and steps required to do that is on [Example Multi card fields Integration](https://github.com/paypal/paypal-sdk-samples/pull/2).

On this PR we just added the basic steps to have the component working but not with all the details.

2021-12-01 18:57 UTC, nbierdeman commented
@leogedler, I created a public repo w/ my test pages, in case it's helpful in troubleshooting the errors I was getting: https://github.com/nbierdeman/card-fields-integration-steps-test-pages

2021-12-01 19:18 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
@nbierdeman I have pushed a fix for this.

2021-12-01 19:19 UTC, leogedler commented
@nbierdeman thanks! I'll give it a look.

2021-12-01 20:32 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
Nice! Works for me. Any idea why your original code didn't work though? It seems like it should. 🤔

2021-12-01 20:56 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
@leogedler, my test page has the following code. Do you see anything wrong with it?

>     cardFields.NumberField({
>       style: customStyles,
>       onChange: ({isValid, errors}) => {
>         console.log('onchange number: ', isValid, errors);
>       }
>     }).render(cardNumberContainer);
> 
>     cardFields.CVVField({
>       style: customStyles,
>       onChange: ({isValid, errors}) => {
>         console.log('onchange cvv: ', isValid, errors);
>       }
>     }).render(cardCvvContainer);
> 
>     cardFields.ExpiryField({
>       style: customStyles,
>       onChange: ({isValid, errors}) => {
>         console.log('onchange expiry: ', isValid, errors);
>       }
>     }).render(cardExpiryContainer);

2021-12-01 20:57 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
Here's the link to the full test page: https://github.com/nbierdeman/card-fields-integration-steps-test-pages/blob/main/multi-card-fields-sample-integration.html

2021-12-01 21:03 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
@nbierdeman yes, it seems that because the parent component could have children, in this case the `NumberField`, `CVVField`, `ExpiryField` it doesn't accept direct/chained rendering.

First we need to instantiated and then render it.

This is not the same for the children that can be direct/chained rendered.

2021-12-01 21:05 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
@nbierdeman if you are using the exact code as the one shared it will fail because of this ---> https://github.com/nbierdeman/card-fields-integration-steps-test-pages/blob/main/multi-card-fields-sample-integration.html#L10

You are pointing to prod but remember that the latest changes for the multi card fields haven't been deployed yet to prod.

Try using your local JS SDK.

2021-12-01 21:15 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
I was wondering that, but then was confused, since rendering `NumberField` and `ExpiryField` work fine if I comment out `CVVField`.

2021-12-01 21:17 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +        cardField.submit().then(() => {
Ah, gotcha. Thanks for explaining that!

2021-12-01 21:17 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    const customStyles = {
@rsdighe76 probably we will need a wrapper component similar to the one used on the Drop-in element from Braintree.

As mentioned by @crookedneighbor, this appears to be the next step if we follow Braintree / Stripe approach.

This wrapper component could accept themes to modify the out of the box experience, but as I see it (and @crookedneighbor can correct me if I'm wrong) we first need to polish the component that we have and then we can start working on that.

As it is right now we can add styles via the style object option and also via direct container styling and we can offer some default styles for the single card fields but floating labels and icons are not supported yet.

2021-12-01 21:34 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    }).render(cardCvvContainer);
@leogedler, I'm able to render `CVVField` when using a local development script, so I'll go ahead and resolve this conversation.

Here's a screenshot though of how I can successfully render `NumberField` and `ExpiryField` if I comment out `CVVField` while using a production script. 😆 

![Screen Shot 2021-12-01 at 2 32 11 PM](https://user-images.githubusercontent.com/20399044/144317614-1228f9fa-b292-4b64-af0e-4e4e2f7b6fe1.png)

2021-12-01 22:03 UTC, nbierdeman approved these changes
Awesome work, @leogedler! I left a few more minor, non-blocking comments, but this looks good to go to me. 🚀

2021-12-01 22:03 UTC, nbierdeman commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +        <button id="button">Submit</button>
How about this to match the single card fields integration steps?
```suggestion
        <button id="button" type="button">Submit</button>
```

2021-12-02 00:29 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +<script src="https://www.paypal.com/sdk/js?client-id=test&components=card-fields&intent=capture"></script>
why do we need to differentiate - the intent is part of Create Order why does it need to be here as well - @crookedneighbor this is probably a carry over from existing JS can we chat with Daniel on why we need to continue with this at least in this specific examples.

2021-12-02 00:48 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 3. Initialize the parent cardFields component and pass in createOrder and onApprove
Why does one need to create an order to instantiate the Card Field ?

2021-12-02 00:48 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 4. Initialize card fields components, call render for each field, and pass in the styles object
k

2021-12-02 00:48 UTC, rsdighe76 commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +    const customStyles = {
ic

2021-12-02 15:45 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +#### 3. Initialize the parent cardFields component and pass in createOrder and onApprove
@rsdighe76 the order is not created when the cardField is instantiated, the requirement is to pass in the function that will create the order once the user clicks `submit`.

The order gets created after submit and the complete calling sequence is:

`createOrder` -> `onApprove` -> `onCapture`.

2021-12-02 15:45 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +        <button id="button">Submit</button>
@nbierdeman got it, all add the type for the button.

2021-12-02 15:45 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-multi-card-fields.md
> +    <div id="multi-transactional-card-field">
@nbierdeman sure, I'll change it.

2021-12-02 15:50 UTC, leogedler commented on spec/client/javascript/components/card-fields/sample-integration-single-card-fields.md
> +#### 3. Initialize the cardFields component, pass in createOrder, onApprove, and the styles object, and call render
@rsdighe76 for the single card field the styles need to be passed during the parent component instantiation (CardFields).

What we pass in is an object, we could separate the step when we add the styles to the object from when we add the `createOrder` and `onApprove` functions but this doesn't make much sense here.

Usually in JS we add all the properties to an object in a single step, that is why you see here this step passing the styles and the functions.

2021-12-06 20:18 UTC, nbierdeman commented
@leogedler, mind rebasing with `main` to see if CI passes?

2021-12-06 20:33 UTC, merged