Lazily fix tests for testing CI
paypal/paypal-sdk-spec pull request #80
Opened 2021-12-02 20:43 UTC by nbierdeman

### DO NOT MERGE - TESTING CI

2021-12-02 21:07 UTC, crookedneighbor commented on spec/client/javascript/standards/components.md
> +    const component = /* await */ paypal.Component({
For these, is it angry that it's not in an async function?

2021-12-02 21:16 UTC, nbierdeman commented on spec/client/javascript/standards/components.md
> +    const component = /* await */ paypal.Component({
I’m guessing that’s the case. I wonder if `operation()` and `Component()` would need to be declared w/ async? I can give that a try.

2021-12-02 21:59 UTC, nbierdeman commented on spec/client/javascript/standards/components.md
> +    const component = /* await */ paypal.Component({
Oh, yeah, `operation()` and `Component()` are defined on the `paypal` object. 🤔

2021-12-02 22:12 UTC, leogedler commented
LGTM

2021-12-02 22:12 UTC, leogedler approved these changes
LGTM

2021-12-06 18:09 UTC, nbierdeman commented
@crookedneighbor, I implemented your TS ignore errors suggestion, and it solved the `await` errors when testing locally. Assuming CI passes, I think this is ready for your final review.

2021-12-06 18:59 UTC, crookedneighbor commented on spec/client/javascript/callbacks/createSubscription.md
> +        __TBD__: () => { /* logic here */ }
```suggestion
        // TBD
```

2021-12-06 19:07 UTC, crookedneighbor requested changes
This is looking good. Just had one change I want to see around the `__TBD__` bit, then it's good to merge.

2021-12-06 19:49 UTC, nbierdeman commented on spec/client/javascript/callbacks/createSubscription.md
> +        __TBD__: () => { /* logic here */ }
@crookedneighbor, a value is required for the tests to pass, so I set it to the string `'TBD'`. Are you cool with that?

2021-12-06 20:16 UTC, crookedneighbor commented on spec/client/javascript/callbacks/createSubscription.md
> +        __TBD__: () => { /* logic here */ }
Yeah, that's fine

2021-12-06 20:16 UTC, merged